export enum HTTPErrorType {
  UNAUTHORISED_ACCESS = 'UNAUTHORISED_ACCESS',
  UNAUTHENTICATED_REQUEST = 'UNAUTHENTICATED_REQUEST',
  AUTO_DISPLAY = 'AUTO_DISPLAY',
  REGULAR = 'REGULAR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  SERVER_ERROR = 'SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
